version: 2.1

jobs:
  build:
    working_directory: ~/BitfinexClient
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew dependencies
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest